### ISSUE TITLE
URL in readme.md not working

### ISSUE THREAD

**Issue by Chaprnks** [MRepoApp/magisk-modules-alt-repo#2]
## Use in MRepo
```
https://raw.githubusercontent.com/MRepoApp/magisk-modules-alt-repo/main/
```

## Result
`400: Invalid request`

![invalidrequest](https://github.com/MRepoApp/magisk-modules-alt-repo/assets/6340970/eb6d8b58-a215-42e8-9ce6-25e4499dcd83)

**Comment by SanmerDev** [comment]
This is normal!

**Comment by dbz-at-google** [comment]
It also doesn't work in MRepo
