### ISSUE TITLE
Required value 'version' missing

### ISSUE THREAD

**Issue by LazyHatGuy** [MRepoApp/magisk-modules-alt-repo#3]
When I try to add this repo to MRepo I get the following error

![Screenshot_20240627-000617_MRepo](https://github.com/MRepoApp/magisk-modules-alt-repo/assets/1010359/dbfc42e1-1e35-40b7-9da1-e0fe705fdded)

**Comment by SanmerDev** [comment]
This requires MRepo 2.5.0+
