### ISSUE TITLE
zram-swap-manager is not present?

### ISSUE THREAD

**Issue by ClockGen** [MRepoApp/magisk-modules-alt-repo#6]
Hello, upstream magisk-modules-alt-repo includes zram-swap-manager module (https://github.com/Magisk-Modules-Alt-Repo/zram-swap-manager), however it's not in this repo. Could it be because its upstream repo is different (https://github.com/VR-25/zram-swap-manager)?

**Comment by SanmerDev** [comment]
That's true, zram-swap-manager is too old in [Magisk Modules Alt Repo](https://github.com/Magisk-Modules-Alt-Repo/zram-swap-manager).
